import { Song } from './store';

// Curated song list inspired by classic hits - using iTunes Search API for previews
export const SONG_CATALOG: Song[] = [
  {
    id: '1',
    title: 'Hey Jude',
    artist: 'The Beatles',
    year: 1968,
    previewUrl: 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/1e/3d/e9/1e3de9a1-e3b5-8c8d-1e1f-b8c0e8b1c7a1/mzaf_8539056550449257056.plus.aac.p.m4a',
    albumArt: null,
  },
  {
    id: '2',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    year: 1975,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '3',
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    year: 1982,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '4',
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    year: 1991,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '5',
    title: 'Purple Rain',
    artist: 'Prince',
    year: 1984,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '6',
    title: 'Like a Rolling Stone',
    artist: 'Bob Dylan',
    year: 1965,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '7',
    title: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    year: 1971,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '8',
    title: 'Hotel California',
    artist: 'Eagles',
    year: 1977,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '9',
    title: 'Yesterday',
    artist: 'The Beatles',
    year: 1965,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '10',
    title: 'Imagine',
    artist: 'John Lennon',
    year: 1971,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '11',
    title: 'What\'s Going On',
    artist: 'Marvin Gaye',
    year: 1971,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '12',
    title: 'Respect',
    artist: 'Aretha Franklin',
    year: 1967,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '13',
    title: 'Johnny B. Goode',
    artist: 'Chuck Berry',
    year: 1958,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '14',
    title: 'Good Vibrations',
    artist: 'The Beach Boys',
    year: 1966,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '15',
    title: 'Born to Run',
    artist: 'Bruce Springsteen',
    year: 1975,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '16',
    title: 'Papa Was a Rollin\' Stone',
    artist: 'The Temptations',
    year: 1972,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '17',
    title: 'Superstition',
    artist: 'Stevie Wonder',
    year: 1972,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '18',
    title: 'Dancing Queen',
    artist: 'ABBA',
    year: 1976,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '19',
    title: 'Beat It',
    artist: 'Michael Jackson',
    year: 1982,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '20',
    title: 'Like a Prayer',
    artist: 'Madonna',
    year: 1989,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '21',
    title: 'Enter Sandman',
    artist: 'Metallica',
    year: 1991,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '22',
    title: 'Losing My Religion',
    artist: 'R.E.M.',
    year: 1991,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '23',
    title: 'Black',
    artist: 'Pearl Jam',
    year: 1991,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '24',
    title: 'Creep',
    artist: 'Radiohead',
    year: 1992,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '25',
    title: 'Wonderwall',
    artist: 'Oasis',
    year: 1995,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '26',
    title: 'Karma Police',
    artist: 'Radiohead',
    year: 1997,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '27',
    title: 'No Scrubs',
    artist: 'TLC',
    year: 1999,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '28',
    title: 'Say My Name',
    artist: "Destiny's Child",
    year: 1999,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '29',
    title: 'Crazy in Love',
    artist: 'Beyoncé',
    year: 2003,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '30',
    title: 'Umbrella',
    artist: 'Rihanna',
    year: 2007,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '31',
    title: 'Rolling in the Deep',
    artist: 'Adele',
    year: 2010,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '32',
    title: 'Blurred Lines',
    artist: 'Robin Thicke',
    year: 2013,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '33',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    year: 2017,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '34',
    title: 'Old Town Road',
    artist: 'Lil Nas X',
    year: 2019,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '35',
    title: 'drivers license',
    artist: 'Olivia Rodrigo',
    year: 2021,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '36',
    title: 'Penny Lane',
    artist: 'The Beatles',
    year: 1967,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '37',
    title: 'Let It Be',
    artist: 'The Beatles',
    year: 1970,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '38',
    title: 'Under Pressure',
    artist: 'Queen & David Bowie',
    year: 1981,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '39',
    title: 'We Will Rock You',
    artist: 'Queen',
    year: 1977,
    previewUrl: null,
    albumArt: null,
  },
  {
    id: '40',
    title: 'Don\'t Stop Me Now',
    artist: 'Queen',
    year: 1978,
    previewUrl: null,
    albumArt: null,
  },
];

export function getRandomSong(usedIds: Set<string>): Song {
  const available = SONG_CATALOG.filter(s => !usedIds.has(s.id));
  const pool = available.length > 0 ? available : SONG_CATALOG;
  return pool[Math.floor(Math.random() * pool.length)];
}

export function getInitialSong(index: number): Song {
  return SONG_CATALOG[index % SONG_CATALOG.length];
}
